# This file is synced from the `Homebrew/.github` repository, and
# modified for this `PikachuEXE/homebrew-FreeTube` repository.

name: actionlint

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*.ya?ml'
  pull_request:
    paths:
      - '.github/workflows/*.ya?ml'

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: "actionlint-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_ENV_HINTS: 1

permissions: {}

jobs:
  workflow_syntax:
    if: github.repository_owner == 'PikachuEXE'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up Homebrew
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: false

      - name: Install tools
        run: brew install actionlint shellcheck

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up actionlint
        run: echo "::add-matcher::$(brew --repository)/.github/actionlint-matcher.json"

      - run: actionlint
