name: Update Homebrew Tap

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  update-homebrew-cask:
    runs-on: macos-14

    env:
      TAP: "pikachuexe/freetube"
      CASK: "pikachuexe-freetube"

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          revoke_token: true
          permissions: "contents:write, metadata:read, pull_requests:write"

      - name: Bump Cask Definition
        env:
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_GITHUB_API_TOKEN: "${{ steps.get_workflow_token.outputs.token }}"
        run: |
          brew tap "$TAP"
          brew bump --open-pr --casks "$TAP/$CASK"