name: Update Homebrew Tap

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  update-homebrew-cask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses:
          actions/checkout@v4

      - name: Download Latest Release File
        id: download_files
        uses: robinraju/release-downloader@v1.9
        with:
          latest: true
          preRelease: true
          fileName: "*.dmg"
          tarBall: false
          zipBall: false
          out-file-path: "downloads"

      - name: Generate checksums
        uses: Solratic/checksum-action@v1
        with:
          pattern: "downloads/*.dmg"
          suffix: "sha256"

      - name: Get Checksum
        id: get_checksum
        run: echo "checksum=$(cat ${{ fromJson(steps.download_files.outputs.downloaded_files)[0] }}.sha256)" >> $GITHUB_OUTPUT

      - name: Echo Checksum
        run: echo ${{ steps.get_checksum.outputs.checksum }}
