name: Update Homebrew Tap

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  update-homebrew-cask:
    runs-on: ubuntu-latest

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          revoke_token: true
          permissions: "contents:write, metadata:read, pull_requests:write"

      - name: Update Homebrew Cask
        uses: eugenesvk/action-homebrew-bump-cask@3.8.4
        with:
          token: "${{ steps.get_workflow_token.outputs.token }}"
          tap: PikachuEXE/homebrew-FreeTube
          cask: pikachuexe-freetube
