name: Update Homebrew Tap

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  update-homebrew-cask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses:
          actions/checkout@v4

      - name: Download Latest Release File
        id: download_files
        uses: robinraju/release-downloader@v1.9
        with:
          latest: true
          preRelease: true
          fileName: "*.dmg"
          tarBall: false
          zipBall: false
          out-file-path: "downloads"

      - name: Generate Checksums
        uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: sha256
          file-name: checksums.txt

      - name: Get Checksum
        id: gen_checksum
        run: echo "checksum=$(cat checksums.txt)" >> $GITHUB_OUTPUT

      - name: Echo Checksum
        run: echo ${{ steps.get_checksum.outputs.checksum }}
